# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'banK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 7.0' 
  pod 'Charts'
  # Pods for banK

  target 'banKTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
